plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-48-1
exclude_patterns:
  - "!spec/"
  - "spec/vcr_cassettes"
checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false
