plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-48-1
exclude_patterns:
  - "!spec/"
  - "spec/vcr_cassettes"
checks:
  similar-code:
    config:
      threshold: 5
  identical-code:
    config:
      threshold: 5
