AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineOperationIndentation:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false
